services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/Harmoni.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - Harmoni-db

  Harmoni-db:
    image: postgres:latest
    container_name: Harmoni.Db
    environment:
      - POSTGRES_DB=Harmoni
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
