# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  connexaapi:
    image: connexaapi
    build:
      context: .
      dockerfile: src/Connexa.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5074:5074
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
