@Connexa_Api_HostAddress = http://localhost:5074

POST  {{Connexa_Api_HostAddress}}/login/
Accept: application/json

Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}
 

###


